version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'kotlin-postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=task_list_data'
