spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        ddl-auto: validate
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.xml
